CLI Wc and Process commands
eshelukhina/HSE2022-SD pull request #7
Opened 2022-02-05 20:51 UTC by egiptipavel

2022-02-05 21:24 UTC, DanielGabitov requested changes

2022-02-05 21:24 UTC, DanielGabitov commented on Commands/cat.py
> +    def execute(self, context: Context):
Нет документации

2022-02-05 21:24 UTC, DanielGabitov commented on Commands/cat.py
>  class Cat:
Не нашел тестов

2022-02-05 21:24 UTC, DanielGabitov commented on Executor/context.py
> +        self.error = ''
Кажется, логичней хранить не пустую строку а None

2022-02-05 21:24 UTC, DanielGabitov commented on Executor/test/test_file_manager.py
> +import tempfile
Очень круто!

2022-02-05 21:24 UTC, DanielGabitov commented on Executor/file_manager.py
> +    def get_directory_content(path_to_directory):
Очень красивый join, но кажется было бы логичней здесь возвращать список файлов, а переносы строк добавит тот, кому нужно

2022-02-05 21:24 UTC, DanielGabitov commented on Commands/wc.py
> +                context.error = 'wc: No such file'
What file?

2022-02-05 21:24 UTC, DanielGabitov commented on Commands/cat.py
> +            context.state += FileManager.get_file_content(arg) + '\n'
Перенос строки в конце команды кажется лишним. Его будет добавлять кто-то на уровне выше а не команда. Например: пользователь вводит пустую строку.

2022-02-05 21:24 UTC, DanielGabitov commented on Commands/wc.py
> +            context.state += str(lines) + ' ' + str(words) + ' ' + str(num_bytes) + '\n'
Лишний перенос строки

2022-02-05 21:24 UTC, DanielGabitov commented on Commands/cat.py
> +                context.error = 'cat: No such file'
What file?

2022-02-05 21:24 UTC, DanielGabitov commented on Commands/test/test_wc.py
> +import os
Было бы прикольно сгенерировать случайный файл и затем с помощью subprocess вызвать cat и сравнить что сходится

2022-02-05 21:24 UTC, DanielGabitov commented on Commands/test/test_wc.py
> +import os
Но я понимаю, что это too deep... Но было бы прикольно...

2022-02-05 21:25 UTC, DanielGabitov commented
В целом оч круто! Спасибо за красивый код перед сном

2022-02-06 09:44 UTC, egiptipavel commented on Commands/cat.py
> +    def execute(self, context: Context):
Написал

2022-02-06 09:44 UTC, egiptipavel commented on Commands/cat.py
>  class Cat:
Добавил

2022-02-06 09:44 UTC, egiptipavel commented on Executor/context.py
> +        self.error = ''
Теперь там Optional

2022-02-06 09:44 UTC, egiptipavel commented on Executor/test/test_file_manager.py
> +import tempfile
Благодарю

2022-02-06 09:45 UTC, egiptipavel commented on Executor/file_manager.py
> +    def get_directory_content(path_to_directory):
Исправил

2022-02-06 09:45 UTC, egiptipavel commented on Commands/wc.py
> +                context.error = 'wc: No such file'
Добавил

2022-02-06 09:45 UTC, egiptipavel commented on Commands/cat.py
> +            context.state += FileManager.get_file_content(arg) + '\n'
Убрал

2022-02-06 09:45 UTC, egiptipavel commented on Commands/wc.py
> +            context.state += str(lines) + ' ' + str(words) + ' ' + str(num_bytes) + '\n'
Убрал

2022-02-06 09:45 UTC, egiptipavel commented on Commands/cat.py
> +                context.error = 'cat: No such file'
Добавил

2022-02-06 09:45 UTC, egiptipavel commented on Commands/test/test_wc.py
> +import os
Мне лень...

2022-02-06 09:54 UTC, DanielGabitov requested changes

2022-02-06 09:54 UTC, DanielGabitov commented on Commands/cat.py
> +                context.error = Optional.of('cat: {}: No such file'.format(arg))
f'cat: {arg}: No such file'

2022-02-06 09:54 UTC, DanielGabitov commented on Commands/test/test_wc.py
> +        assert context.state.get() == '1 1 6 {}'.format(path)
f'1 1 6 {path}'

2022-02-06 09:54 UTC, DanielGabitov commented on Commands/test/test_wc.py
> +        assert context.state.get() == '1 2 11 {}'.format(path)
И тут

2022-02-06 09:54 UTC, DanielGabitov commented on Commands/test/test_wc.py
> +        assert context.state.get() == '1 2 11 {0}\n1 2 11 {1}'.format(path1, path2)
И тут

2022-02-06 09:54 UTC, DanielGabitov commented on Commands/wc.py
> +                context.error = Optional.of('wc: {}: No such file'.format(arg))
И тут

2022-02-06 09:54 UTC, DanielGabitov commented on Commands/wc.py
> +        result = result[:-1]
Не очевидно сходу что ты делаешь. Варианта два: добавить комментарий или складывать результат в список, а затем joinить. Мне больше второй нравится :)

2022-02-06 10:22 UTC, DanielGabitov commented
LGTM

2022-02-06 10:23 UTC, merged